### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by eliasdorneles** [Lothiraldan/balto#1]
Hello Boris !

It was nice meeting you at Pycon FR! :)

So I was just trying to run the example, and I got the following TypeError:

```
$ balto . 
Process Process-1:
Traceback (most recent call last):
  File "/home/elias/.pythonz/pythons/CPython-3.7.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/elias/.pythonz/pythons/CPython-3.7.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
TypeError: server() missing 1 required positional argument: 'runner'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f343c13a0f0>
```

Here is python version and dependencies info:

```
$ python --version
Python 3.7.0
$ pip freeze
aiodocker==0.14.0
aiohttp==3.4.4
aiohttp-json-rpc==0.11.2
async-timeout==3.0.0
atomicwrites==1.2.1
attrs==18.2.0
-e git+https://github.com/Lothiraldan/balto.git@88194c0fb4d9053b000be3c75eeba6c08971ae23#egg=balto
certifi==2018.8.24
chardet==3.0.4
docker==3.5.0
docker-pycreds==0.3.0
idna==2.7
more-itertools==4.3.0
multidict==4.4.2
npyscreen==4.10.5
pluggy==0.7.1
prompt-toolkit==2.0.5
py==1.6.0
pytest==3.8.2
requests==2.19.1
six==1.11.0
urllib3==1.23
urwid==2.0.1
wcwidth==0.1.7
websocket-client==0.53.0
yarl==1.2.6
```

Are you getting the same thing?

**Comment by eliasdorneles** [comment]
After looking at the code with a bit more patience, I spotted the bug -- here is a PR to fix it: https://github.com/Lothiraldan/balto/pull/2
