### ISSUE TITLE
How to start the React app?

### ISSUE THREAD

**Issue by eliasdorneles** [Lothiraldan/balto#3]
Hello !

I've been trying and failing to start the React app -- is this documented somewhere in any way?

It feels like there might be something missing from the repo.

When I try: `cd  balto/web_interfaces/balto_react &&npm install && npm run build`, I get:

    Module not found: Error: Can't resolve '../time' in '/home/elias/src/balto/balto/web_interfaces/balto_react/src/components'

**Comment by Lothiraldan** [comment]
Indeed, I forgot to commit a file, thank you for your issue!

I will update the README, the easiest way to hack on the interface is by launching: `yarn start` in the `balto/web_interfaces/balto_react` repository

**Comment by eliasdorneles** [comment]
Cool, thanks!

So I've just synced w/ master and I'm now running into some issue related to the way the command is built:

```
$ balto --debug -v . 
======== Running on http://0.0.0.0:8889 ========
(Press CTRL+C to quit)
[2018-10-08 18:34:45,279] /home/elias/src/balto/balto/server.py:91: Run ALL
[2018-10-08 18:34:45,279] /home/elias/src/balto/balto/server.py:112: Forwarding to 1 clients: {'_type': 'run_start', 'run_id': '3dcb25ce8c3f40b2af1013fe402d65eb'}
Message {'run_id': '3dcb25ce8c3f40b2af1013fe402d65eb'}
[2018-10-08 18:34:45,279] /home/elias/src/balto/balto/runners/subprocess_runner.py:33: Launching "None '{}'" from working directory '.'
[2018-10-08 18:34:45,284] /home/elias/src/balto/balto/runners/base.py:46: Invalid line: '/bin/sh: 1: None: not found'
Traceback (most recent call last):
  File "/home/elias/src/balto/balto/runners/base.py", line 44, in parse_line
    data = json.loads(decodedline)
  File "/home/elias/.pythonz/pythons/CPython-3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/elias/.pythonz/pythons/CPython-3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/elias/.pythonz/pythons/CPython-3.7.0/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2018-10-08 18:34:45,292] /home/elias/src/balto/balto/runners/subprocess_runner.py:55: CMD "None '{}'" exited with return code: 127
[2018-10-08 18:34:45,293] /home/elias/src/balto/balto/server.py:112: Forwarding to 1 clients: {'_type': 'run_stop', 'run_id': '3dcb25ce8c3f40b2af1013fe402d65eb', 'return_code': 127}
Message {'run_id': '3dcb25ce8c3f40b2af1013fe402d65eb', 'return_code': 127}
```

**Comment by eliasdorneles** [comment]
Btw, thank you for working on this! :)

I'm willing to invest some time in improving it (e.g. I can help packaging to ship to PyPI, etc).

I gotta go now, but I'll continue tomorrow.

**Comment by Lothiraldan** [comment]
@eliasdorneles Thank you for testing.

This particular error is when Balto cannot find the tool in the configuration file. If you use the tool `pytest`, it is looking for the binary `pytest-litf` in your path. I plan to improve the error message in this case asap.

**Comment by eliasdorneles** [comment]
Thanks, yes, I was missing the `pytest-litf` plugin.
It works now. :)
